### PR TITLE
Updates for DCGM 3.3.0

### PR DESCRIPTION
**Pull request by glowkey**
Also includes fix/formatting for WatchPidFields from helinfan

### CODE REVIEW

**Comment by rswhollan** [comment]
Have you looked at testing/python3/internal_scripts/nvswitch_counter_monitor.py? It uses some of the fields you are deleting. Well, from the python equivalent of dcgm_fields.h, but that should follow dcgm_fields.h.

**Review by nikkon-dev — APPROVED** [review]

**Comment by glowkey** [comment]
The deleted fields are no longer present in dcgm_fields.h. Most likely nvswitch_counter_monitor.py needs to be udpated.

**Comment by rswhollan** [comment]
No, more than that: dcgm_fields.py has to match dcgm_fields.h. I did not see it in your merge request. Nik: this looks incomplete.

**Comment by nikkon-dev** [comment]
> No, more than that: dcgm_fields.py has to match dcgm_fields.h. I did not see it in your merge request. Nik: this looks incomplete.

This is not the dcgm repo. The changes you are referring to are irrelevant for Go bindings.

**Pull request merged**
